import {beforeEach,describe,expect,it,vi} from 'vitest'
const mocks=vi.hoisted(()=>({env:{RESEND_WEBHOOK_SECRET:'test_svix_secret'},verify:vi.fn(),parse:vi.fn(),recordVerified:vi.fn(),recordRejected:vi.fn(),process:vi.fn()}))
vi.mock('@/lib/env',()=>({env:mocks.env}))
vi.mock('svix',()=>({Webhook:class {verify=mocks.verify}}))
vi.mock('@/server/services/email-delivery.service',()=>({parseEmailProviderWebhookPayload:mocks.parse}))
vi.mock('@/server/services/webhook-delivery.service',()=>({recordVerifiedWebhookDelivery:mocks.recordVerified,recordRejectedWebhook:mocks.recordRejected}))
vi.mock('@/server/services/inbound-webhook-processing.service',()=>({processInboundWebhook:mocks.process}))
import {POST} from './route'
const payload=JSON.stringify({type:'email.bounced',data:{email_id:'email_1'}})
const request=(signed=true)=>new Request('http://localhost/api/webhooks/email-provider',{method:'POST',headers:signed?{'svix-id':'evt_existing','svix-timestamp':'123','svix-signature':'signature'}:{},body:payload})
describe('email webhook ingress',()=>{
 beforeEach(()=>{vi.resetAllMocks();mocks.env.RESEND_WEBHOOK_SECRET='test_svix_secret';mocks.parse.mockReturnValue(JSON.parse(payload));mocks.recordVerified.mockResolvedValue({id:'delivery',status:'RECEIVED'});mocks.process.mockResolvedValue({status:'PROCESSED'})})
 it('verifies before recording a stable provider event ID',async()=>{expect((await POST(request())).status).toBe(200);expect(mocks.verify).toHaveBeenCalledWith(payload,{id:'evt_existing',timestamp:'123',signature:'signature'});expect(mocks.verify.mock.invocationCallOrder[0]).toBeLessThan(mocks.recordVerified.mock.invocationCallOrder[0]);expect(mocks.recordVerified).toHaveBeenCalledWith({provider:'resend',providerEventId:'evt_existing',eventType:'email.bounced',payload});expect(mocks.process).toHaveBeenCalledExactlyOnceWith('delivery')})
 it('never records or claims canonical state after an invalid signature',async()=>{mocks.verify.mockImplementation(()=>{throw new Error('invalid')});expect((await POST(request())).status).toBe(400);expect(mocks.recordRejected).toHaveBeenCalledWith(expect.objectContaining({provider:'resend',payload}));expect(mocks.parse).not.toHaveBeenCalled();expect(mocks.recordVerified).not.toHaveBeenCalled();expect(mocks.process).not.toHaveBeenCalled()})
 it('requires all signature headers',async()=>{expect((await POST(request(false))).status).toBe(400);expect(mocks.verify).not.toHaveBeenCalled();expect(mocks.recordVerified).not.toHaveBeenCalled()})
 it('fails closed without the environment webhook secret',async()=>{mocks.env.RESEND_WEBHOOK_SECRET='';expect((await POST(request())).status).toBe(503);expect(mocks.verify).not.toHaveBeenCalled()})
 it('rejects invalid verified payloads',async()=>{mocks.parse.mockReturnValue(null);expect((await POST(request())).status).toBe(400);expect(mocks.recordVerified).not.toHaveBeenCalled()})
 it('acknowledges processed deliveries without processing them again',async()=>{mocks.recordVerified.mockResolvedValue({id:'delivery',status:'PROCESSED'});expect((await POST(request())).status).toBe(200);expect(mocks.process).not.toHaveBeenCalled()})
 it.each([[null,202],[{status:'RETRY_PENDING'},500]])('returns the processing outcome',async(result,status)=>{mocks.process.mockResolvedValue(result);expect((await POST(request())).status).toBe(status)})
})
