import {beforeEach,describe,expect,it,vi} from 'vitest'
const mocks=vi.hoisted(()=>({env:{STRIPE_WEBHOOK_SECRET:'whsec_test'},verify:vi.fn(),parse:vi.fn(),recordVerified:vi.fn(),recordRejected:vi.fn(),process:vi.fn()}))
vi.mock('@/lib/env',()=>({env:mocks.env}))
vi.mock('@/lib/stripe',()=>({verifyStripeWebhookSignature:mocks.verify}))
vi.mock('@/server/services/stripe-webhook.service',()=>({parseStripeWebhookEventPayload:mocks.parse}))
vi.mock('@/server/services/webhook-delivery.service',()=>({recordVerifiedWebhookDelivery:mocks.recordVerified,recordRejectedWebhook:mocks.recordRejected}))
vi.mock('@/server/services/inbound-webhook-processing.service',()=>({processInboundWebhook:mocks.process}))
import {POST} from './route'
const payload=JSON.stringify({id:'evt_existing',type:'payment_intent.succeeded',data:{object:{id:'pi_1'}}})
const request=()=>new Request('http://localhost/api/webhooks/stripe',{method:'POST',headers:{'stripe-signature':'signature'},body:payload})
describe('Stripe webhook ingress',()=>{
 beforeEach(()=>{vi.resetAllMocks();mocks.env.STRIPE_WEBHOOK_SECRET='whsec_test';mocks.parse.mockReturnValue(JSON.parse(payload));mocks.recordVerified.mockResolvedValue({id:'delivery',status:'RECEIVED'});mocks.process.mockResolvedValue({status:'PROCESSED'})})
 it('verifies the raw body with the environment secret before recording or claiming the canonical event',async()=>{expect((await POST(request())).status).toBe(200);expect(mocks.verify).toHaveBeenCalledWith(payload,'signature','whsec_test');expect(mocks.verify.mock.invocationCallOrder[0]).toBeLessThan(mocks.recordVerified.mock.invocationCallOrder[0]);expect(mocks.recordVerified).toHaveBeenCalledWith({provider:'stripe',providerEventId:'evt_existing',eventType:'payment_intent.succeeded',payload});expect(mocks.process).toHaveBeenCalledExactlyOnceWith('delivery')})
 it('cannot mutate the canonical event when an attacker copies its ID with an invalid signature',async()=>{mocks.verify.mockImplementation(()=>{throw new Error('invalid signature')});const response=await POST(request());expect(response.status).toBe(400);expect(mocks.recordRejected).toHaveBeenCalledWith({provider:'stripe',payload,error:'Stripe webhook signature verification failed'});expect(mocks.parse).not.toHaveBeenCalled();expect(mocks.recordVerified).not.toHaveBeenCalled();expect(mocks.process).not.toHaveBeenCalled()})
 it('fails closed when webhook env configuration is missing',async()=>{mocks.env.STRIPE_WEBHOOK_SECRET='';expect((await POST(request())).status).toBe(503);expect(mocks.verify).not.toHaveBeenCalled();expect(mocks.recordRejected).not.toHaveBeenCalled()})
 it('rejects malformed verified payloads',async()=>{mocks.parse.mockReturnValue(null);expect((await POST(request())).status).toBe(400);expect(mocks.recordVerified).not.toHaveBeenCalled()})
 it('acknowledges duplicate processed receipts without reprocessing',async()=>{mocks.recordVerified.mockResolvedValue({id:'delivery',status:'PROCESSED'});expect((await POST(request())).status).toBe(200);expect(mocks.process).not.toHaveBeenCalled()})
 it('returns accepted when another worker owns the claim or a retry is scheduled',async()=>{mocks.process.mockResolvedValue(null);expect((await POST(request())).status).toBe(202)})
 it('returns failure when durable processing fails',async()=>{mocks.process.mockResolvedValue({status:'RETRY_PENDING'});expect((await POST(request())).status).toBe(500)})
})
