import {beforeEach,describe,expect,it,vi} from 'vitest'
const mocks=vi.hoisted(()=>({claim:vi.fn(),processed:vi.fn(),failed:vi.fn(),parseStripe:vi.fn(),stripe:vi.fn(),parseEmail:vi.fn(),email:vi.fn(),parseShipping:vi.fn(),shipping:vi.fn()}))
vi.mock('./webhook-delivery.service',()=>({claimWebhookDelivery:mocks.claim,markWebhookDeliveryProcessed:mocks.processed,markWebhookDeliveryFailed:mocks.failed}))
vi.mock('./stripe-webhook.service',()=>({parseStripeWebhookEventPayload:mocks.parseStripe,processStripeWebhookEvent:mocks.stripe}))
vi.mock('./email-delivery.service',()=>({parseEmailProviderWebhookPayload:mocks.parseEmail,applyEmailProviderWebhookEvent:mocks.email}))
vi.mock('@/server/shipping/shipping-tracking-webhook.service',()=>({parseShippingProviderWebhookPayload:mocks.parseShipping,applyShippingProviderTrackingWebhookEvent:mocks.shipping}))
import {processInboundWebhook} from './inbound-webhook-processing.service'
const delivery={id:'delivery',provider:'stripe',providerEventId:'evt_1',rawPayload:'verified payload',claimToken:'claim'}
const claim={provider:'stripe',providerEventId:'evt_1',claimToken:'claim'}
describe('shared inbound processing',()=>{
 beforeEach(()=>{vi.resetAllMocks();mocks.claim.mockResolvedValue(delivery);mocks.parseStripe.mockReturnValue({id:'evt_1'});mocks.processed.mockResolvedValue({status:'PROCESSED',attempts:1});mocks.failed.mockResolvedValue({status:'RETRY_PENDING',attempts:1});mocks.parseEmail.mockReturnValue({type:'email.delivered'});mocks.email.mockResolvedValue({handled:true});mocks.parseShipping.mockReturnValue({eventType:'tracking.updated'});mocks.shipping.mockResolvedValue({handled:true})})
 it('processes verified payload only after winning the same claim used by ingress and replay',async()=>{expect(await processInboundWebhook('delivery',true)).toEqual({id:'delivery',status:'PROCESSED',attempts:1});expect(mocks.claim).toHaveBeenCalledWith('delivery',true);expect(mocks.parseStripe).toHaveBeenCalledWith('verified payload');expect(mocks.processed).toHaveBeenCalledWith(claim)})
 it('does nothing when another worker owns the delivery',async()=>{mocks.claim.mockResolvedValue(null);expect(await processInboundWebhook('delivery')).toBeNull();expect(mocks.stripe).not.toHaveBeenCalled();expect(mocks.processed).not.toHaveBeenCalled();expect(mocks.failed).not.toHaveBeenCalled()})
 it('marks mismatched stored Stripe IDs non-retryable without creating an order',async()=>{mocks.parseStripe.mockReturnValue({id:'different_event'});await processInboundWebhook('delivery');expect(mocks.stripe).not.toHaveBeenCalled();expect(mocks.failed).toHaveBeenCalledWith({...claim,error:'Stored Stripe event is invalid',retryable:false})})
 it('schedules transient business failures with the claim token',async()=>{mocks.stripe.mockRejectedValue(new Error('temporary database error'));await processInboundWebhook('delivery');expect(mocks.failed).toHaveBeenCalledWith({...claim,error:'temporary database error',retryable:true});expect(mocks.processed).not.toHaveBeenCalled()})
 it.each(['resend','shipping.shippo','shipping.easypost'])('uses the shared retry path for %s',async(provider)=>{mocks.claim.mockResolvedValue({...delivery,provider});expect((await processInboundWebhook('delivery'))?.status).toBe('PROCESSED');expect(provider==='resend'?mocks.email:mocks.shipping).toHaveBeenCalledOnce();expect(mocks.processed).toHaveBeenCalledWith({...claim,provider})})
 it('acknowledges unsupported email events without retry loops',async()=>{mocks.claim.mockResolvedValue({...delivery,provider:'resend'});mocks.email.mockResolvedValue({handled:false,reason:'UNSUPPORTED_EVENT'});expect((await processInboundWebhook('delivery'))?.status).toBe('PROCESSED')})
 it('retries provider events whose referenced delivery is not available yet',async()=>{mocks.claim.mockResolvedValue({...delivery,provider:'resend'});mocks.email.mockResolvedValue({handled:false,reason:'DELIVERY_NOT_FOUND'});await processInboundWebhook('delivery');expect(mocks.failed).toHaveBeenCalledWith(expect.objectContaining({retryable:true,error:'DELIVERY_NOT_FOUND'}))})
 it('does not report success after losing finalization ownership',async()=>{mocks.processed.mockResolvedValue(null);expect(await processInboundWebhook('delivery')).toBeNull()})
})
