import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

function read(relativePath: string) {
  return fs.readFileSync(path.join(process.cwd(), relativePath), 'utf8')
}

describe('Promotions workspace copy', () => {
  it('uses a clean promotions header with one primary create action', () => {
    const file = read('src/components/discounts/DiscountsWorkspace.js')
    expect(file).toContain('title="Promotions"')
    expect(file).toContain('Create and manage discount codes and automatic offers.')
    expect(file).toContain('Create promotion')
    expect(file).not.toContain('<AdminPageHeader\r\n          actions={(')
    expect(file).not.toContain('<AdminPageHeader\n          actions={(')
    expect(file).toContain('<div className={styles.listHeader}>')
    expect(file).toContain("label: 'All'")
    expect(file).toContain("label: 'Discount codes'")
    expect(file).toContain("label: 'Automatic'")
    expect(file.match(/<AdminButton onClick=\{openCreateFlow\} size="sm" variant="primary">/g)?.length).toBe(1)
    expect(file).not.toContain('Browse discount codes and automatic offers from one promotions workspace.')
  })

  it('renders a unified promotions table instead of separate discount-code and automatic-offer sections', () => {
    const file = read('src/components/discounts/DiscountsWorkspace.js')
    expect(file).toContain("header: 'Name'")
    expect(file).toContain("header: 'Method'")
    expect(file).toContain("header: 'Type'")
    expect(file).toContain("header: 'Status'")
    expect(file).toContain("header: 'Usage'")
    expect(file).toContain("header: 'Updated'")
    expect(file).toContain("header: 'Actions'")
    expect(file).toContain("source: 'discount-code'")
    expect(file).toContain("source: 'smart-promotion'")
    expect(file).toContain("method: 'Code'")
    expect(file).toContain("method: 'Automatic'")
    expect(file).toContain('Search promotions...')
    expect(file).not.toContain('<h2>Discount codes</h2>')
    expect(file).not.toContain('<h2>Automatic offers</h2>')
  })

  it('keeps the method-type-details create flow and legacy discount-code restrictions', () => {
    const workspace = read('src/components/discounts/DiscountsWorkspace.js')
    const data = read('src/lib/discountsData.js')
    expect(workspace).toContain('How should this promotion work?')
    expect(workspace).toContain('Choose whether customers enter a code or Doopify applies the offer automatically.')
    expect(workspace).toContain('Continue to type')
    expect(workspace).toContain('Choose discount code type')
    expect(workspace).toContain('Choose automatic offer type')
    expect(workspace).toContain('Continue to details')
    expect(workspace).toContain("LEGACY_DISCOUNT_METHODS = ['amount off products', 'amount off order', 'free shipping']")
    expect(workspace).toContain('Looking for Buy X Get Y, Free Gift, or product group savings? Use an automatic promotion type.')
    expect(data).toContain("DISCOUNT_METHODS = ['amount off products', 'amount off order', 'free shipping']")
  })

  it('keeps selection card copy concise and accessible', () => {
    const file = read('src/components/discounts/DiscountsWorkspace.js')
    expect(file).toContain("badge: 'Code'")
    expect(file).toContain("badge: 'Automatic'")
    expect(file).toContain("title: 'Discount code'")
    expect(file).toContain("title: 'Automatic offer'")
    expect(file).toContain("title: 'Amount off products'")
    expect(file).toContain("title: 'Product group discount'")
    expect(file).toContain('Best for: SUMMER20, VIP offers, free shipping.')
    expect(file).toContain('Best for: bundles, Buy X Get Y, free gifts.')
    expect(file).toContain('Discount selected products or variants.')
    expect(file).toContain("These offers apply when the customer's cart matches your rules.")
    expect(file).toContain("V1 note: Buy X Get Y and Free Gift do not auto-add reward items. Reward items must already be in the customer's cart.")
    expect(file).not.toContain('Reward items must already be in cart for Buy X Get Y and Free Gift in V1.')
    expect(file).toContain('aria-checked={selectedMethod === choice.id}')
    expect(file).toContain("data-selected={selectedMethod === choice.id ? 'true' : 'false'}")
    expect(file).toContain('role="radio"')
  })

  it('preserves smart promotion detail copy and edit/disable behavior', () => {
    const file = read('src/components/discounts/DiscountsWorkspace.js')
    const smartFile = read('src/components/discounts/AutomaticPromotionsWorkspace.js')
    const pickerFile = read('src/components/discounts/PromotionVariantCommandPicker.tsx')
    expect(file).toContain("openSmartEditDrawer(row.sourceId)")
    expect(file).toContain("disableSmartPromotion(row.sourceId)")
    expect(file).toContain("window.confirm(")
    expect(smartFile).toContain('title="Required cart items"')
    expect(smartFile).toContain('Selected required items')
    expect(smartFile).toContain('Browse products')
    expect(smartFile).toContain('No required items selected.')
    expect(smartFile).toContain('Choose the products customers must have in cart.')
    expect(smartFile).toContain("title={draft.type === 'PRODUCT_GROUP_DISCOUNT' ? 'Discount settings' : 'Reward items'}")
    expect(smartFile).toContain('Selected reward items')
    expect(smartFile).toContain('Browse rewards')
    expect(smartFile).toContain('No reward items selected.')
    expect(smartFile).toContain('Choose what receives the discount.')
    expect(smartFile).toContain("Reward items must already be in the customer's cart. Auto-add is not enabled in V1.")
    expect(pickerFile).toContain('type="checkbox"')
    expect(smartFile).toContain('Add selected')
    expect(pickerFile).toContain('Already selected')
  })

  it('documents the smart promotion picker interaction contract', () => {
    const smartFile = read('src/components/discounts/AutomaticPromotionsWorkspace.js')
    const pickerFile = read('src/components/discounts/PromotionVariantCommandPicker.tsx')
    const workspace = read('src/components/discounts/DiscountsWorkspace.js')
    expect(smartFile).toContain('pickerTitle="Browse products"')
    expect(smartFile).toContain('pickerTitle="Browse rewards"')
    expect(smartFile).toContain('onBrowse={() => onOpenPicker(\'qualifiers\')}')
    expect(smartFile).toContain('onBrowse={() => onOpenPicker(\'rewards\')}')
    expect(smartFile).toContain('onSearch={() => onSearchCatalog(\'qualifiers\')}')
    expect(smartFile).toContain('onSearch={() => onSearchCatalog(\'rewards\')}')
    expect(smartFile).toContain('onOpenChange={(nextOpen) => {')
    expect(pickerFile).toContain('role="dialog"')
    expect(pickerFile).toContain('aria-modal="true"')
    expect(pickerFile).toContain('type="checkbox"')
    expect(pickerFile).toContain('disabled={!pendingCount}')
    expect(pickerFile).toContain('onOpenChange(false)')
    expect(pickerFile).toContain('Loading products...')
    expect(pickerFile).toContain('<AdminButton onClick={onSearch} size="sm" variant="secondary">')
    expect(workspace).toContain("window.addEventListener('doopify-open-promotion-create'")
  })

  it('keeps type-specific smart promotion sections clear', () => {
    const smartFile = read('src/components/discounts/AutomaticPromotionsWorkspace.js')
    expect(smartFile).toContain("const showRewards = draft.type !== 'PRODUCT_GROUP_DISCOUNT'")
    expect(smartFile).toContain('!showRewards ? (')
    expect(smartFile).toContain('This discount applies to the required cart items selected above.')
    expect(smartFile).toContain('Choose the products that receive the discount when the required cart items are present.')
    expect(smartFile).toContain('Choose the product that becomes free when the required cart items are present.')
    expect(smartFile).toContain("Gift items must already be in the customer's cart. Auto-add is not enabled in V1.")
    expect(smartFile).toContain('className={styles.lockedRewardSummary} aria-label="Reward discount"')
    expect(smartFile).toContain('<strong>Free</strong>')
  })

  it('keeps selected rows editable and removable without changing payload helper shape', () => {
    const smartFile = read('src/components/discounts/AutomaticPromotionsWorkspace.js')
    expect(smartFile).toContain('aria-label={`${quantityLabel} for ${row.productTitle} ${row.variantTitle}`}')
    expect(smartFile).toContain('quantityLabel="Required quantity"')
    expect(smartFile).toContain('quantityLabel="Reward quantity"')
    expect(smartFile).toContain('onRemoveSelection(\'qualifiers\', variantId)')
    expect(smartFile).toContain('onRemoveSelection(\'rewards\', variantId)')
    expect(smartFile).toContain('[section]: current[section].concat({')
    expect(smartFile).toContain('const existing = current[section].find((row) => row.variantId === variant.id)')
  })

  it('keeps unified-list styling and stronger picker styling intact', () => {
    const workspace = read('src/components/discounts/DiscountsWorkspace.module.css')
    const automatic = read('src/app/_styles/dashboard-theme.css')
    expect(workspace).toContain('.listHeader')
    expect(workspace).toContain('.methodPill')
    expect(workspace).toContain('.rowActions')
    expect(workspace).toContain('.offerChoiceList')
    expect(workspace).toContain('.offerChoiceCard:hover')
    expect(workspace).toContain('.offerChoiceCardActive')
    expect(workspace).toContain('.offerChoiceBadge')
    expect(workspace).toContain('.offerChoiceRadio::after')
    expect(workspace).toContain('.offerChoiceSelectionTag')
    expect(workspace).toContain('.offerChoiceNote')
    expect(workspace).toContain('padding-bottom: 6rem;')
    expect(automatic).toContain('.promotion-command-picker')
    expect(automatic).toContain('.promotion-command-picker__results')
    expect(automatic).toContain('.promotion-command-picker__loading-note')
    expect(automatic).toContain('.promotion-command-picker__variant-row')
    expect(automatic).toContain('.promotion-command-picker__footer')
    expect(automatic).toContain('.admin-command-palette__group')
  })
})
